### ISSUE TITLE
Add Code of Conduct

### ISSUE THREAD

**Issue by alexjoverm** [AlicanteFrontend/alicantefrontend.github.io#11]
We need to add a Code of Conduct (CoC) for Alicante Frontend's community. It should represent the  social and behavioural practises to keep a healthy community.

Some points to:
 - It must be in Spanish
 - It must include a [Creative Commons license](https://creativecommons.org/choose/) as free/open as possible
 - Make it concise, but complete
 - A very good example is [Python Spain's](https://github.com/python-spain/web/blob/master/CODE_OF_CONDUCT.md). [Codenares](https://github.com/codenares/codenares/wiki/C%C3%B3digo-de-conducta) one is good as well, and more concise. Probably a mix of both fits perfectly.

**Comment by LauraBonmati** [comment]
working on this =)

**Comment by alexjoverm** [comment]
via @aarongarciah: a good resource for this is the [conduct library](https://github.com/sindresorhus/conduct) which generates [this Code of Conduct](https://www.contributor-covenant.org/version/1/4/code-of-conduct.md). It looks good to me, at least as a start.

**Comment by AlvYuste** [comment]
Closed by #20
