### ISSUE TITLE
UI inspiration

### ISSUE THREAD

**Issue by aarongarciah** [AlicanteFrontend/alicantefrontend.github.io#14]
Some links to inspire ourselves 😄  Feel free to comment or add new links.

- [meetcleo.com](https://meetcleo.com/)
- [timothyachumba.com](http://timothyachumba.com/)
- [usecontrast.com](https://usecontrast.com/)
- [oak.is](https://oak.is/)
- [surge.sh](http://surge.sh/)

**Comment by Blledo** [comment]
Me mataras pero... no me gusta ninguna.

**Comment by aarongarciah** [comment]
Legit. But please, add some links 😄

**Comment by Blledo** [comment]
Yo, muchas veces, cuando estoy falto de inspiración me paseo por [dribbble](https://dribbble.com) observando que propone la gente y voy pillando mini conceptos de cada uno.

**Comment by alexjoverm** [comment]
I personally like a lot the [zeppelin](https://github.com/gdg-x/zeppelin) template that Google Developer Groups used for their conference. Not to use it, but for inspiration.
