### ISSUE TITLE
Build an animated background header effect using HTML5 canvas, CSS3 gradients and the logo

### ISSUE THREAD

**Issue by gazpachu** [AlicanteFrontend/alicantefrontend.github.io#15]
The initial idea is to create a composition with the logo, a colourful background and some interactive geometric shapes. It would be great to mix concepts from Alicante and front-end technologies.

Some useful resources:

- https://codepen.io/MyXoToD/pen/ilwuD
- https://tympanus.net/codrops/2014/09/23/animated-background-headers/
- http://maxwellito.github.io/vivus/
- https://github.com/williamngan/pt
- https://threejs.org/

**Comment by aarongarciah** [comment]
Keep in mind that we'll probably need to define previously the look and feel of the website.

**Comment by gazpachu** [comment]
I've been playing with this and it's quite cool! http://vincentgarreau.com/particles.js/

**Comment by aarongarciah** [comment]
Looks cool 😄 Let's see how it fits with the design once we've got one. The idea is to keep the website as lightweight as possible, so better if we do not use any library.

**Comment by AlvYuste** [comment]
A great and simple example by our friend from Spotify: https://codepen.io/jmperez/pen/rxxRRg

**Comment by AlvYuste** [comment]
Another great technique to keep in mind: https://codepen.io/ainalem/pen/WXdPQP

**Comment by AlvYuste** [comment]
The [great work](https://codepen.io/sego/pen/qVeqYw) of @PacoSegovia may close this issue. 👌

**Comment by AlvYuste** [comment]
Still, let's keep it open until it is definitely merged with master.
