### ISSUE TITLE
Configure Netlify to cache static assets

### ISSUE THREAD

**Issue by aarongarciah** [AlicanteFrontend/alicantefrontend.github.io#18]
See more info about how to configure Netlify's cache at https://www.netlify.com/docs/headers-and-basic-auth/#custom-headers

And see WebPageTest results at http://www.webpagetest.org/performance_optimization.php?test=171023_JS_62d69baa5b4d0f145bda0c7f68d2c102&run=2#cache_static_content

**Comment by ladislavsulc** [comment]
+1
